version: '3.9'
services:
  frontend:
    image: frontend
    build:
      context: ./
      dockerfile: apps/frontend/Dockerfile
    ports:
      - '3000:3000'
  backend:
    image: backend
    build:
      context: ./
      dockerfile: apps/backend/Dockerfile
    ports:
      - '3333:3333'
